
export const HOME_PAGE_TITLE_1 = "Boards";

export const HOME_PAGE_BODY_1 = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Turpis massa tincidunt dui ut ornare lectus sit. Tortor dignissim convallis aenean et tortor at risus viverra. Posuere ac ut consequat semper viverra. Vitae justo eget magna fermentum iaculis eu non. Nec dui nunc mattis enim ut tellus. A diam maecenas sed enim ut sem. In hac habitasse platea dictumst vestibulum rhoncus. Blandit libero volutpat sed cras. Pulvinar etiam non quam lacus suspendisse faucibus. Orci dapibus ultrices in iaculis nunc sed augue lacus viverra. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Pellentesque dignissim enim sit amet venenatis urna. A arcu cursus vitae congue mauris rhoncus aenean vel elit. Egestas sed tempus urna et pharetra. Donec ac odio tempor orci dapibus ultrices in iaculis. Semper auctor neque vitae tempus quam.

Eu consequat ac felis donec et odio pellentesque diam. Justo eget magna fermentum iaculis eu non diam. Id velit ut tortor pretium viverra suspendisse. A diam sollicitudin tempor id eu nisl nunc mi. Varius vel pharetra vel turpis nunc. Nisi vitae suscipit tellus mauris a diam maecenas sed enim. Orci phasellus egestas tellus rutrum. Et netus et malesuada fames ac turpis egestas sed. Eu augue ut lectus arcu bibendum at varius. Euismod in pellentesque massa placerat. Sit amet nisl suscipit adipiscing bibendum est. Ac auctor augue mauris augue neque gravida in fermentum et. Elementum curabitur vitae nunc sed velit dignissim sodales. Dictumst quisque sagittis purus sit amet volutpat consequat. Consectetur a erat nam at lectus. Duis at tellus at urna condimentum mattis pellentesque id nibh.
`;

export const HOME_PAGE_BODY_2 = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus et netus et. Amet mattis vulputate enim nulla aliquet porttitor. Eget est lorem ipsum dolor. In tellus integer feugiat scelerisque. Ornare quam viverra orci sagittis eu volutpat odio facilisis mauris. Massa eget egestas purus viverra accumsan in nisl nisi. Egestas purus viverra accumsan in nisl nisi scelerisque. Arcu non odio euismod lacinia at quis risus. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Sapien faucibus et molestie ac feugiat. Vehicula ipsum a arcu cursus vitae congue. Pulvinar neque laoreet suspendisse interdum consectetur libero.

Orci nulla pellentesque dignissim enim sit amet venenatis. Sed augue lacus viverra vitae congue. Pulvinar mattis nunc sed blandit libero volutpat sed. Pharetra vel turpis nunc eget lorem dolor sed viverra. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Ullamcorper velit sed ullamcorper morbi. Nisi lacus sed viverra tellus in hac habitasse platea dictumst. Ligula ullamcorper malesuada proin libero nunc consequat interdum varius. Sit amet nulla facilisi morbi tempus iaculis urna id. Sed arcu non odio euismod lacinia at quis risus. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Lorem donec massa sapien faucibus et molestie.

Ullamcorper sit amet risus nullam eget felis eget nunc. Ipsum nunc aliquet bibendum enim. Id donec ultrices tincidunt arcu non sodales neque sodales ut. Commodo odio aenean sed adipiscing diam donec adipiscing tristique risus. Commodo viverra maecenas accumsan lacus vel facilisis. Lacinia quis vel eros donec ac. Turpis egestas sed tempus urna et pharetra pharetra. Gravida rutrum quisque non tellus orci ac auctor. Diam sollicitudin tempor id eu nisl nunc. Turpis tincidunt id aliquet risus feugiat in ante metus dictum. Sit amet consectetur adipiscing elit ut. Malesuada fames ac turpis egestas sed tempus urna. Sit amet dictum sit amet justo donec enim diam. Non tellus orci ac auctor augue mauris. Quis auctor elit sed vulputate mi. Libero volutpat sed cras ornare arcu dui vivamus arcu felis.

Habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Nam at lectus urna duis convallis convallis tellus id interdum. Convallis posuere morbi leo urna. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Urna nec tincidunt praesent semper feugiat nibh. Bibendum est ultricies integer quis auctor elit. Tristique nulla aliquet enim tortor at. Gravida dictum fusce ut placerat orci nulla pellentesque dignissim. Id volutpat lacus laoreet non curabitur gravida. Senectus et netus et malesuada fames. Dui id ornare arcu odio ut sem nulla. Diam donec adipiscing tristique risus nec.

Fusce ut placerat orci nulla. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Amet venenatis urna cursus eget nunc scelerisque viverra. Tristique senectus et netus et. Sem et tortor consequat id porta nibh. Tristique senectus et netus et malesuada. Non tellus orci ac auctor augue mauris augue neque. Felis imperdiet proin fermentum leo vel orci porta non pulvinar. Eu lobortis elementum nibh tellus. Nec feugiat in fermentum posuere urna nec tincidunt praesent. Imperdiet dui accumsan sit amet nulla facilisi. Rhoncus dolor purus non enim praesent elementum facilisis leo. Nunc non blandit massa enim nec dui. Facilisi morbi tempus iaculis urna id volutpat. Maecenas ultricies mi eget mauris pharetra. Porta lorem mollis aliquam ut porttitor leo a diam sollicitudin. Maecenas volutpat blandit aliquam etiam. Dolor morbi non arcu risus quis varius.
`;

export const ABOUT_PAGE_BODY_1 = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eget gravida cum sociis natoque penatibus et magnis. Cum sociis natoque penatibus et magnis dis parturient montes nascetur. Mi sit amet mauris commodo quis imperdiet massa. Ut etiam sit amet nisl purus in mollis nunc. Iaculis nunc sed augue lacus viverra. Praesent semper feugiat nibh sed pulvinar proin gravida hendrerit. Quis risus sed vulputate odio ut enim blandit. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Vulputate eu scelerisque felis imperdiet proin fermentum leo vel orci. Vitae proin sagittis nisl rhoncus mattis rhoncus. Mi bibendum neque egestas congue quisque egestas. Sem fringilla ut morbi tincidunt augue interdum. Vestibulum morbi blandit cursus risus at ultrices. Diam quam nulla porttitor massa id.

Id volutpat lacus laoreet non curabitur gravida. Duis convallis convallis tellus id interdum velit laoreet. Libero justo laoreet sit amet cursus. Turpis in eu mi bibendum. Nibh nisl condimentum id venenatis a condimentum vitae sapien. Leo urna molestie at elementum eu facilisis sed odio morbi. Sit amet dictum sit amet justo. Porttitor lacus luctus accumsan tortor posuere ac ut consequat semper. Augue eget arcu dictum varius duis. Interdum velit euismod in pellentesque massa placerat duis ultricies lacus. Eu scelerisque felis imperdiet proin fermentum. Eget magna fermentum iaculis eu non diam phasellus vestibulum lorem. Vitae purus faucibus ornare suspendisse. In fermentum posuere urna nec tincidunt praesent. In hendrerit gravida rutrum quisque. Tellus rutrum tellus pellentesque eu tincidunt.

Suscipit adipiscing bibendum est ultricies integer. Vitae et leo duis ut diam quam nulla porttitor massa. Odio tempor orci dapibus ultrices in iaculis. Nunc consequat interdum varius sit. Turpis massa sed elementum tempus egestas sed sed risus pretium. Mauris in aliquam sem fringilla. Ipsum a arcu cursus vitae congue. Ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est velit. Euismod elementum nisi quis eleifend quam adipiscing vitae proin. Viverra vitae congue eu consequat ac felis donec et odio. Et netus et malesuada fames ac turpis egestas integer. Penatibus et magnis dis parturient montes. Dui sapien eget mi proin sed libero enim sed. Lectus sit amet est placerat. Morbi enim nunc faucibus a.

Accumsan in nisl nisi scelerisque eu. Purus gravida quis blandit turpis cursus. Aliquam ultrices sagittis orci a. Dolor sit amet consectetur adipiscing elit ut. Facilisi morbi tempus iaculis urna id. Curabitur vitae nunc sed velit dignissim sodales ut eu sem. Potenti nullam ac tortor vitae purus. Ac odio tempor orci dapibus ultrices in iaculis nunc. Vestibulum sed arcu non odio euismod lacinia at. Lacus sed turpis tincidunt id aliquet risus feugiat in ante. Integer quis auctor elit sed. Suspendisse in est ante in nibh mauris cursus mattis molestie. Donec ac odio tempor orci dapibus ultrices in iaculis. Iaculis at erat pellentesque adipiscing commodo elit. Sit amet dictum sit amet justo. Morbi tristique senectus et netus. Cursus mattis molestie a iaculis at erat pellentesque adipiscing commodo. Quis viverra nibh cras pulvinar mattis nunc sed. Pulvinar elementum integer enim neque volutpat. Nunc eget lorem dolor sed.

Morbi tempus iaculis urna id volutpat lacus laoreet non. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Hendrerit gravida rutrum quisque non tellus orci. Donec massa sapien faucibus et. Tincidunt eget nullam non nisi est sit. Nisi lacus sed viverra tellus in hac. Volutpat blandit aliquam etiam erat velit scelerisque in. Ornare lectus sit amet est placerat in egestas. Mi eget mauris pharetra et ultrices neque ornare aenean. Et ligula ullamcorper malesuada proin libero nunc consequat interdum. Magna fermentum iaculis eu non diam phasellus vestibulum lorem. In hac habitasse platea dictumst. Ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Mauris commodo quis imperdiet massa tincidunt nunc. Urna neque viverra justo nec ultrices dui. Turpis nunc eget lorem dolor sed viverra ipsum nunc. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Magnis dis parturient montes nascetur ridiculus mus mauris.

Urna porttitor rhoncus dolor purus. Vitae et leo duis ut diam. Et netus et malesuada fames. Nisl purus in mollis nunc sed id semper. Laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt. Duis tristique sollicitudin nibh sit amet commodo nulla. Nunc sed augue lacus viverra vitae. Sapien et ligula ullamcorper malesuada proin libero nunc consequat. A lacus vestibulum sed arcu non odio euismod. Morbi tincidunt ornare massa eget egestas purus viverra accumsan in. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Massa vitae tortor condimentum lacinia quis vel eros donec ac.

Quisque id diam vel quam elementum pulvinar. Iaculis eu non diam phasellus vestibulum lorem. Diam sollicitudin tempor id eu nisl nunc mi. Sed ullamcorper morbi tincidunt ornare. Sodales neque sodales ut etiam sit amet nisl purus in. Quis blandit turpis cursus in hac habitasse. Pharetra et ultrices neque ornare aenean euismod elementum. Laoreet id donec ultrices tincidunt arcu. Tincidunt tortor aliquam nulla facilisi cras fermentum odio eu feugiat. Vitae elementum curabitur vitae nunc sed velit dignissim sodales ut. Id venenatis a condimentum vitae sapien.

Purus semper eget duis at. Tincidunt arcu non sodales neque sodales ut etiam sit. Pellentesque sit amet porttitor eget dolor morbi non arcu risus. Risus commodo viverra maecenas accumsan lacus vel. Eget duis at tellus at urna. Donec pretium vulputate sapien nec sagittis aliquam. Lacus vestibulum sed arcu non odio euismod. Laoreet non curabitur gravida arcu ac tortor. Aliquet bibendum enim facilisis gravida neque convallis a. Mi eget mauris pharetra et ultrices. Eu consequat ac felis donec et. Hendrerit gravida rutrum quisque non tellus. Elementum tempus egestas sed sed risus pretium quam vulputate dignissim. Enim diam vulputate ut pharetra. Mauris vitae ultricies leo integer. Mauris sit amet massa vitae. Sed adipiscing diam donec adipiscing. Morbi blandit cursus risus at ultrices mi tempus. Pretium viverra suspendisse potenti nullam ac tortor vitae. Risus feugiat in ante metus dictum at tempor commodo.

Justo laoreet sit amet cursus sit amet dictum sit. Varius vel pharetra vel turpis nunc eget lorem. Nunc lobortis mattis aliquam faucibus purus in massa tempor nec. Morbi non arcu risus quis varius quam quisque id. Adipiscing tristique risus nec feugiat in fermentum. Egestas dui id ornare arcu odio ut. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus. In aliquam sem fringilla ut morbi tincidunt. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. Magna fringilla urna porttitor rhoncus. Congue quisque egestas diam in arcu. Arcu cursus vitae congue mauris rhoncus aenean vel. Sed turpis tincidunt id aliquet risus feugiat in ante. Tellus cras adipiscing enim eu turpis egestas. Dignissim enim sit amet venenatis urna cursus eget nunc.

Enim nec dui nunc mattis enim ut. Cursus eget nunc scelerisque viverra mauris in. Sed enim ut sem viverra aliquet eget. Sit amet est placerat in egestas erat imperdiet. Bibendum est ultricies integer quis auctor elit sed. Faucibus pulvinar elementum integer enim. Ultricies integer quis auctor elit sed vulputate. Turpis cursus in hac habitasse platea dictumst quisque. Sit amet aliquam id diam maecenas ultricies mi eget mauris. Nisi quis eleifend quam adipiscing vitae proin.
`;

